Added target framework to netstandard2.0
jbogard/MediatR pull request #821
Opened 2023-01-14 14:52 UTC by maniglia

Please consider adding netstandard2.0 as a target framework if you can.

2023-01-17 15:08 UTC, jbogard commented
I...don't understand how this compiles. The docs say `IAsyncEnumerable` only supports `netstandard2.1` and above:

![image](https://user-images.githubusercontent.com/104498/212934724-c80eecb0-7c7b-4cd3-babd-2992a4d8090a.png)

I'll do some more digging but if it's working with `netstandard2.0` then I'll just downgrade to that altogether.

2023-01-17 15:17 UTC, jbogard commented
Welp it gets pulled in with the Microsoft.Bcl.AsyncInterfaces package (which I did not know existed). Derp. We can just target `netstandard2.0` directly.

2023-01-17 15:17 UTC, jbogard requested changes

2023-01-18 22:06 UTC, jbogard approved these changes

2023-01-18 23:17 UTC, maniglia commented
Unfortunately I have some problems compiling the project, i get the following message:
_MinVer : error MINVER1007: "git" is not present in PATH._
Even though I installed git and entered the environment variable.

2023-01-19 14:04 UTC, jbogard approved these changes

2023-01-31 17:06 UTC, merged